=== NourKannou/tp_xml/tpxml/src/xsd/BanqueService.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/BanqueService"
	xmlns:tns="http://www.example.org/BanqueService"
	elementFormDefault="qualified">

	<element name="BanqueService">
		<complexType>
			<sequence>
				<element name="conversion" type="conversion"></element>
				<element name="getComptes" type="compte" minOccurs="1"
					maxOccurs="unbounded">

				</element>
				<element name="getCompte" type="compte">

				</element>
			</sequence>
		</complexType>
	</element>

	<complexType name="conversion">
		<sequence>
			<element name="montant" type="double">
			</element>
		</sequence>
	</complexType>


	<complexType name="compte">
		<sequence>
			<element name="solde" type="double"></element>
			<element name="code" type="integer"></element>
			<element name="dataCreation" type="date"></element>

		</sequence>
	</complexType>

</schema>

=== NourKannou/tp_xml/tpxml/bin/transformation/BanqueService.xml
<?xml version="1.0" encoding="UTF-8"?>

<BanqueService>
	xmlns:tns="http://www.example.org/BanqueService"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/BanqueService BanqueService.xsd ">

	<conversion>
		<montant>1400</montant>
	</conversion>

	<getComptes>
	
		<solde>123</solde>
		<code>7</code>
		<dataCreation>2001-01-01</dataCreation>
		
		<solde>126</solde>
		<code>7</code>
		<dataCreation>1966-01-01</dataCreation>
		
		<solde>123</solde>
		<code>7</code>
		<dataCreation>2030-01-01</dataCreation>
	
	</getComptes>

	<getCompte>
		<solde>445</solde>
		<code>1</code>
		<dataCreation>2001-01-01</dataCreation>
	</getCompte>

</BanqueService>

=== NourKannou/tp_xml/tpxml/src/xsd/BanqueService.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:BanqueService xmlns:tns="http://www.example.org/BanqueService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/BanqueService BanqueService.xsd ">
  
  <tns:conversion>
    <tns:montant>1400</tns:montant>
  </tns:conversion>
 
  <tns:getComptes>
    <tns:solde>123</tns:solde>
    <tns:code>7</tns:code>
    <tns:dataCreation>2001-01-01</tns:dataCreation>
  </tns:getComptes>
  
  <tns:getCompte>
    <tns:solde>445</tns:solde>
    <tns:code>1</tns:code>
    <tns:dataCreation>2001-01-01</tns:dataCreation>
  </tns:getCompte>

</tns:BanqueService>
